spring.application.name=accounts

spring.datasource.url=jdbc:postgresql://localhost:5432/accounts
spring.datasource.username=postgres
spring.datasource.password=postgres

# Hibernate properties
spring.jpa.hibernate.ddl-auto=create-drop

user.api.url=https://fo69fu407j.execute-api.eu-central-1.amazonaws.com/live/users/
user.api.key=xjtDAaDTXi9drr2OTvM5vaDHnk8WLs0H2EIYdWWT

email.api.url=https://fo69fu407j.execute-api.eu-central-1.amazonaws.com/live/email/
email.api.key=xjtDAaDTXi9drr2OTvM5vaDHnk8WLs0H2EIYdWWT